"""Initial Schema

Revision ID: 319ccba38e49
Revises: 
Create Date: 2026-05-13 12:21:49.962011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319ccba38e49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_name', sa.String(length=100), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('password_initial_change', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_email')
    )
    op.create_table('semester',
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('semester_name', sa.String(length=100), nullable=False),
    sa.Column('swap_allowed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('semester_id')
    )
    op.create_table('student',
    sa.Column('register_number', sa.String(length=20), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('pfp_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('register_number'),
    sa.UniqueConstraint('email')
    )
    op.create_table('batch',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('batch_name', sa.String(length=50), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.semester_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('student_semester_assignment',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('register_number', sa.String(length=20), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('cgpa', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cgpa >= 0 AND cgpa <= 10', name='ck_assignment_cgpa_range'),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.batch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['register_number'], ['student.register_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.semester_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('register_number', 'semester_id', name='uq_assignment_register_semester')
    )
    op.create_table('swap_request',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('requester_assignment_id', sa.Integer(), nullable=False),
    sa.Column('target_assignment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('requester_assignment_id <> target_assignment_id', name='ck_swap_request_different_assignments'),
    sa.ForeignKeyConstraint(['approved_by'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['requester_assignment_id'], ['student_semester_assignment.assignment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_assignment_id'], ['student_semester_assignment.assignment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('swap_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('requester_old_batch', sa.Integer(), nullable=False),
    sa.Column('requester_new_batch', sa.Integer(), nullable=False),
    sa.Column('target_old_batch', sa.Integer(), nullable=False),
    sa.Column('target_new_batch', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['swap_request.request_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_new_batch'], ['batch.batch_id'], ),
    sa.ForeignKeyConstraint(['requester_old_batch'], ['batch.batch_id'], ),
    sa.ForeignKeyConstraint(['target_new_batch'], ['batch.batch_id'], ),
    sa.ForeignKeyConstraint(['target_old_batch'], ['batch.batch_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swap_history')
    op.drop_table('swap_request')
    op.drop_table('student_semester_assignment')
    op.drop_table('batch')
    op.drop_table('student')
    op.drop_table('semester')
    op.drop_table('admin')
    # ### end Alembic commands ###
